<?php

/**
 * @file
 * Create an interface for the library helpdesk
 */

/**
 * Implements hook_menu();
 */
function bibdk_helpdesk_menu() {
  $items['overlay/helpdesk'] = array(
    'title' => t('Help desk'),
    'description' => 'Library helpdesk form.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bibdk_helpdesk_form'),
    'access arguments' => array('access content'),
    'file' => 'bibdk_helpdesk.form.inc',
  );
  return $items;
}

/**
 * Implements hook_block_info().
 */
function bibdk_helpdesk_block_info() {
  $blocks['bibdk-helpdesk-teaser'] = array(
    'info' => t('Bibdk: Helpdesk teaser'),
    'cache' => DRUPAL_NO_CACHE,
    'description' => t('Library helpdesk teaser form.'),
  );
  $blocks['header_action'] = array(
    'info' => t('Bibdk: Helpdesk header action'),
    'description' => t('Link to helpdesk in header region'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function bibdk_helpdesk_block_view($delta = '') {

  $block = array();
  switch ($delta) {
    case 'bibdk-helpdesk-teaser':
      $block['subject'] = t('Library Helpdesk');
      $block['content'] =
          theme('bibdk_helpdesk_block', array(
        'description' => t('You can contact a librarian, if you need a personalized service.'),
        'link' => l(t('Ask Helpdesk'), 'overlay/helpdesk', array(
          'attributes' => array(
            'class' => array('bibdk-popup-link', 'text-white'),
            'rel' => array('userhelp'),
          )
        )),
        'image' => theme_image(array(
          'path' => _bibdk_get_random_helpdesk_image('normal'),
          'attributes' => array(),
        )),
        'title' => t('Ask helpdesk'),
          )
      );
      break;

    case 'header_action':
      $block['subject'] = '<none>';
      $block['content'] = _bibdk_helpdesk_create_render_array($delta);
      break;
  }
  return $block;
}

/**
 * Helper function: Creates render arrays for blocks
 * @return array
 */
function _bibdk_helpdesk_create_render_array($delta) {

  $render = array();

  switch ($delta) {
    case 'header_action':
      $render = array(
        'link' => array(
          '#type' => 'link',
          '#title' => t('Ask Helpdesk'),
          '#href' => 'overlay/helpdesk',
          '#attributes' => array(
            'class' => array('bibdk-popup-link', 'element-target'),
            'rel' => array('userhelp'),
          ),
        ),
        'image' => array(
          '#theme' => 'image',
          '#path' => _bibdk_get_random_helpdesk_image('header'),
        ),
      );
      break;
  }
  return $render;
}

/**
 * Helper function: Returns random image path
 * params: $size is the subfolder within /images/
 */
function _bibdk_get_random_helpdesk_image($size) {
  $images_path = drupal_get_path('module', 'bibdk_helpdesk') . '/images/' . $size;
  $images = file_scan_directory($images_path, '/./', array('key' => 'filename'));
  $image = array_rand($images);

  return $images_path . '/' . $image;
}

/**
 * Implements hook_theme().
 */
function bibdk_helpdesk_theme() {
  $path = drupal_get_path('module', 'bibdk_helpdesk') . '/theme';
  $theme_array = array(
    'bibdk_helpdesk_block' => array(
      'path' => $path,
      'template' => 'bibdk-helpdesk-block',
    ),
    'theme_bibdk_helpdesk_result' => array(
      'render element' => 'form',
      'path' => $path,
      'template' => 'bibdk-helpdesk-result',
    ),
  );
  return $theme_array;
}
